# Generated by Django 5.1.7 on 2025-04-05 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
