# Generated by Django 5.1.7 on 2025-04-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0003_alter_ddsrecord_date_alter_status_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dds.type'),
        ),
    ]
