# Generated by Django 5.1.7 on 2025-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0004_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsrecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
