# Generated by Django 5.1.7 on 2025-04-06 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0005_alter_ddsrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddsrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
